version: "3.4"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    restart: always
  db:
    image: mongo
    volumes:
      - /usr/docker/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      DATABASE_NAME: app
  backend:
    image: app/backend
    build: ../nodejs/
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - db
  frontend:
    image: app/frontend
    build: ../reactjs/
    restart: always
    ports:
      - "3000:3000"
